#===common params===
raw_dir : "rawdata" #rawdata directory
work_dir : "/home/zhaolab/chengsiming/test/github/bulkrna_pipeline2/v0.1.3" #work directory
bulkrna_env : "envs/bulkrna_env.yaml" #conda environment for bulkrna analysis
rbase4_env : "envs/rbase4_env.yaml" #conda environment for r
samples : "samples.txt" #input sample_info file,col1 is group name,col2 is sample name
contrasts : "contrasts.txt" #input contrasts file for difference expression, col1 is case,col2 is control

#===genome index===
genome_index :
  genome : "ref/genome.fa" #genome FA file,default
  gtf : "ref/genes.gtf" #genome annotation file,default
  threads : 2 #number of thread for building reference genome index
  mem_gb : 2 #number of memory(GB)

#===qc params===
qc :
  threads : 2 #number of thread for fastqc
  mem_gb : 2 #number of memory(GB)

#===filter params===
filter :
  threads : 2 #number of thread for fastq trim
  mem_gb : 2 #number of memory(GB)

#===alignment params===
alignment :
  strandness : "F" #specify strand-specific information (unstranded){F,RF,FR}
  threads : 4 #number of thread for alignment
  mem_gb : 2 #number of memory(GB)
sam2bam : 
  threads : 4 #number of thread for sam to bam base on samtools
  mem_gb : 2 #number of memory(GB)

#===quantification===
quanti :
  featuretype : "exon" #[featureCounts params]a character string or a vector of character strings giving the feature type or types used to select rows in the GTF annotation which will be used for read summarization. 'exon' by default. This argument is only applicable when isGTFAnnotationFile is TRUE.Feature types can be found in the third column of a GTF annotation.
  attritype : "gene_id" #[featureCounts params]a character string giving the attribute type in the GTF annotation which will be used to group features (eg. exons) into meta-features (eg. genes). 'gene_id' by default. This argument is only applicable when isGTFAnnotationFile is TRUE. Attributes can be found in the ninth column of a GT annotation.
  ispairend : "TRUE" #[featureCounts params]a logical scalar or a logical vector, indicating whether libraries contain paired-end reads or not.True by default. For any library that contains paired-end reads, the 'countReadPairs' parameter controls if read pairs or reads should be counted.
  strandness : 0 #[featureCounts params]an integer vector indicating if strand-specific read counting should be performed. Length of the vector should be either 1 (meaning that the value is applied to all input files), or equal to the total number of input files provided. Each vector element should have one of the following three values: 0 (unstranded), 1 (stranded) and 2 (reversely stranded). Default value of this parameter is 0 (ie. unstranded read counting is performed for all input files).
  threads : 2 #number of thread for calculate gene count
  mem_gb : 2 #number of memory(GB)
        
